Repository BeanieODM/beanie, pull requests merged in 2023-10, with the labels that each got.

#584 Refactor Encoder
  beanie/odm/queries/find.py
  beanie/odm/utils/dump.py
  beanie/odm/utils/encoder.py
  beanie/odm/utils/pydantic.py
Labels: bug, action requested

#711 Preserve sort/skip/limit for aggregations
  beanie/odm/queries/find.py
  beanie/odm/utils/find.py
  tests/odm/query/test_aggregate.py
Labels: bug

#739 Simplify BsonBinary
  beanie/odm/custom_types/bson/binary.py
  tests/odm/custom_types/test_bson_binary.py
Labels: action requested

#730 fix: issue#728 pydantic_core._pydantic_core.Url object is not iterable
  beanie/odm/utils/encoder.py
  tests/odm/conftest.py
  tests/odm/models.py
  tests/odm/test_encoder.py
Labels: action requested

#741 Replace custom 'hidden=True' field attribute with builtin 'exclude=True'
  beanie/odm/documents.py
  beanie/odm/utils/init.py
  tests/odm/conftest.py
  tests/odm/documents/test_update.py
  tests/odm/models.py
  tests/odm/test_fields.py
Labels: action requested

#734 fix: issue #631
  beanie/odm/utils/relations.py
  tests/odm/test_relations.py
Labels: action requested
